name: 'Actions Test'

on: push

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: actions/checkout@v1
      - name: 'setup python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: 'pip install'
        run: pip install -r requirements.txt
      - name: 'run'
        env:
          P_A: aaa
          P_B: ${{ secrets.PWD }}
        run: python main.py