name: 'Actions Test'

on: 
  push:
  schedule:
    - cron: '0 0/1 * * *' # cron表达式，Actions时区是UTC时间，所以上午9点要往前推8个小时

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: actions/checkout@v1
      - name: 'setup python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: 'pip install'
        run: pip install -r requirements.txt
      - name: 'run'
        env:
          P_A: aaa
          P_B: ${{ secrets.PWD }}
        run: python main.py